#!/usr/bin/env node
/*
 * Regenerates js/brand.data.js from assets/brand-logo.png so the site's
 * brand mark works when opened directly from the filesystem as well as
 * when hosted. Run after changing the logo:  node tools/embed-brand.js
 */
const fs = require('fs');
const path = require('path');

const logoPath = path.join(__dirname, '..', 'assets', 'brand-logo.png');
const b64 = fs.readFileSync(logoPath).toString('base64');

const out = `/* Generated by tools/embed-brand.js — do not edit by hand. */
window.BRAND_LOGO = "data:image/png;base64,${b64}";
`;

const target = path.join(__dirname, '..', 'js', 'brand.data.js');
fs.writeFileSync(target, out);
console.log(`wrote ${target} (${(out.length / 1024).toFixed(1)} KB)`);
