#!/usr/bin/env node
/*
 * Regenerates js/fonts.data.js from the TTFs in fonts/ so the site works
 * when opened directly from the filesystem (no fetch()) as well as when
 * hosted. Run after changing any font file:  node tools/embed-fonts.js
 */
const fs = require('fs');
const path = require('path');

const fontDir = path.join(__dirname, '..', 'fonts');
const read = (f) => fs.readFileSync(path.join(fontDir, f)).toString('base64');

const out = `/* Generated by tools/embed-fonts.js — do not edit by hand. */
window.STATEMENT_FONTS = {
  light: "${read('DejaVuSans-ExtraLight.ttf')}",
  bold: "${read('DejaVuSans-Bold.ttf')}",
  book: "${read('DejaVuSans.ttf')}",
  sans: "${read('LiberationSans-Regular.ttf')}",
  sansBold: "${read('LiberationSans-Bold.ttf')}",
  sansBoldItalic: "${read('LiberationSans-BoldItalic.ttf')}"
};
`;

const target = path.join(__dirname, '..', 'js', 'fonts.data.js');
fs.writeFileSync(target, out);
console.log(`wrote ${target} (${(out.length / 1024 / 1024).toFixed(2)} MB)`);
